CREATE TABLE BRAND (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    CURRENCY VARCHAR(255)
);

CREATE TABLE PRICE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID BIGINT,
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    PRICE_LIST INT,
    PRODUCT_ID BIGINT,
    PRIORITY INT,
    PRICE DOUBLE,
    CURRENCY VARCHAR(255),
    FOREIGN KEY (BRAND_ID) REFERENCES BRAND(ID)
);